# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12y4QVVwMUweAFKK1UMwpTJv84-1oF-1K
"""

ls -la

print("Ok")

print("abc")